# a_tensor_initialization.py

In [25]:
import torch

In [26]:
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


- 위 코드에서 torch.Tensor() 함수는 flat32 타입의 tensor를 반환

In [27]:
t1 = torch.Tensor([1, 2, 3], device='cpu')
# t1_cuda = t1.to(torch.device('cuda'))
t1_mps = t1.to(torch.device('mps'))
print(t1_mps.dtype)
print(t1_mps.device)
print(t1_mps.requires_grad)
print(t1_mps.size())
print(t1_mps.shape)

torch.float32
mps:0
False
torch.Size([3])
torch.Size([3])


- torch.Tensor()에 대한 gpu를 사용예제
- gpu : Nvidia -> cuda, Apple -> mps

In [28]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


- 위 코드에서 torch.tensor() 함수는 주어진 리스트내 원소 타입을 그대로 유지시켜 준다.

In [29]:
a1 = torch.tensor(1)
print(a1.shape, a1.ndim)

torch.Size([]) 0


a1 = torch.tensor(1):
- torch.tensor() 함수는 '[]'생략 가능
- 1이라는 값을 가지는 텐서를 생성
- 이 값은 스칼라이며, 0차원 텐서로 텐서 내에 요소가 없고 단순히 값을 보유

In [30]:
a2 = torch.tensor([1])
print(a2.shape, a2.ndim)

torch.Size([1]) 1


In [31]:
a3 = torch.tensor([1,2,3,4,5])
print(a3.shape, a3.ndim)

torch.Size([5]) 1


In [32]:
a4 = torch.tensor([
    [1],[2], [3], [4], [5]
])
print(a4.shape, a4.ndim)

torch.Size([5, 1]) 2


In [33]:
a5 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


In [34]:
a6 = torch.tensor([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

torch.Size([3, 2, 1]) 3


In [35]:
a7 = torch.tensor([
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

torch.Size([3, 1, 2, 1]) 4


In [36]:
a8 = torch.tensor([
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

torch.Size([3, 1, 2, 3]) 4


In [37]:
a9 = torch.tensor([
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

torch.Size([3, 1, 2, 3, 1]) 5


In [38]:
a10 = torch.tensor([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

torch.Size([4, 5]) 2


In [39]:
a11 = torch.tensor([
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a11.shape, a11.ndim)

torch.Size([4, 1, 5]) 3


In [40]:
a12 = torch.tensor([
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

ValueError: expected sequence of length 3 at dim 3 (got 2)

- tensor의 경우 모든 차원에 대하여 개별 원소의 사이즈에 값이 다를 수 없음

# b_tensor_initialization_copy.py

In [41]:
import torch
import numpy as np

In [50]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


- torch.Tensor()의 경우 List 대하여 float32자료형의 tensor로 변환후 반환
- torch.tensor()의 경우 List 대하여 기존 자료형의 tensor로 변환후 반환
- torch.as_tensor()의 경우 List 대하여 기존 자료형의 tensor로 변환후 반화
- 세 함수 모두 tensor 객체 생성시 기존의 값을 참조하지 않고 별도의 값을 가짐
- 세 함수 모두 List를 인자로 받을 경우 List는 Array의 형태를 유지하고 있어야함

In [45]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


- 세 함수 모두 List와 마찬가지로 np.array를 인자로 받을 수 있음
- torch.as_tensor의 경우 np.array를 인자로 받는 경우 tensor객체 생성시 기존의 값을 참조하여 생성

# c_tensor_initialization_constant_values.py

In [52]:
import torch

In [58]:
t1 = torch.ones(size=(5,))
t1_like = torch.ones_like(input=t1)
print(t1)
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


- torch.ones() : 주어진 size의 tensor를 생성후 모든 값을 1로 초기화, tensor의 자료형은 float32
- torch.ones_like : 주어진 tensor와 동일한 size의 tensor를 생성후 모든 값을 1로 초기화, tensor의 자료형은 주어진 tensor를 따라감

In [55]:
t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2)
print(t2)
print(t2_like)

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


- torch.zeros() : 주어진 size의 tensor를 생성후 모든 값을 0으로 초기화, tensor의 자료형은 float32
- torch.zeros_like : 주어진 tensor와 동일한 size의 tensor를 생성후 모든 값을 0으로 초기화, tensor의 자료형은 주어진 tensor를 따라감

In [59]:
t3 = torch.empty(size=(4,))
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like)

tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])


- torch.empty() : 주어진 size의 tensor를 생성후 메모리를 초기화 하지 않음, 그러므로 해당 값이 꼭 0이 아닐 수 있음, tensor의 자료형은 float32
- torch.empty_like : 주어진 tensor와 동일한 size의 tensor를 생성후 메모리를 초기화 하지 않음, tensor의 자료형은 주어진 tensor를 따라감

In [61]:
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


- torch.eye() : 주어진 size의tensor를 생성후 단위 행렬로 초기화, tensor의 자료형은 float32

# d_tensor_initialization_random_values.py

In [62]:
import torch

In [63]:
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

tensor([[17, 10]])


- torch.randint() : low 값부터(포함) high 값까지(미포함) 주어진 size크기의 텐서를 생성하여 랜덤 값으로 초기화 후 반환, tensor의 자료형은 int

In [64]:
t2 = torch.rand(size=(1, 3))
print(t2)

tensor([[0.9027, 0.7729, 0.8770]])


- torch.rand() : 0부터(포함) 1까지(미포함) 주어진 size크기의 텐서를 생성하여 랜덤 값으로 초기화 후 반환, tensor의 자료형은 float32
- 이때 각 값에 대한 확률은 uniform

In [65]:
t3 = torch.randn(size=(1, 3))
print(t3)

tensor([[-0.3325, -0.0946,  2.1700]])


- torch.randn() : 주어진 size크기의 텐서를 생성하여 랜덤 값으로 초기화 후 반환, tensor의 자료형은 float32
- 이때 각 값에 대한 확률은 평균이 0이고 표준편차가 1인 정규분포의 확률

In [66]:
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

tensor([[ 9.4322, 11.4233],
        [10.4033, 10.9327],
        [ 8.4181, 11.4158]])


- torch.normal() : 주어진 size크기의 텐서를 생성하여 랜덤 값으로 초기화 후 반환, tensor의 자료형은 float32
- 이때 각 값에 대한 확률은 주어진 평균과 표준편차의 정규분포의 확률

In [71]:
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

tensor([0.0000, 2.5000, 5.0000])


- torch.linspace() : 시작점(start), 끝점(end), 그리고 포함할 점의 수(steps)를 입력으로 받아 일정한 간격으로 값을 생성, tensor의 자료형은 float32

In [69]:
t6 = torch.arange(5)
print(t6)

tensor([0, 1, 2, 3, 4])


- torch.arange() : 시작점(start), 끝점(end), 그리고 간격(step)을 입력으로 받아 일정한 간격으로 값을 생성, tensor의 자료형은 자동 결정
- start의 default 값은 0, step의 default 값은 1

In [72]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


- torch.manual_seed() : 난수 생성을 위한 시드(seed)를 설정
- 시드를 설정하면 난수 생성 과정이 예측 가능해지며, 같은 시드를 사용하면 항상 동일한 무작위 결과를 얻을 수 있음

# e_tensor_type_conversion.py

In [73]:
import torch

In [76]:
a = torch.ones((2, 3))
print(a.dtype)
b = torch.ones((2, 3), dtype=torch.int16)
print(b)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


- torch.ones()의 반환 tensor에 대한 기본 자료형은 float32이지만 dtype인자의 값 전달을 통해 자료형은 변경이 가능

In [77]:
c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)


- torch.rand()의 값은 0~1사이 인 값인 반면 위의 결과는 모든 값이 20이 곱해 진 것을 볼 수 있음
- 곱셈에 대하여 broadcast가 가능함

In [78]:
d = b.to(torch.int32)
print(d)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


- tensor의 to() 메소드를 통해 타입이 바뀐 tensor를 만들 수 있음
- to() 메소드를 통해 받은 tensor는 기존 값을 참조하고 있지 않음

In [84]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16
torch.float64
torch.int16
torch.float64
torch.int16
torch.float64
torch.int16


- 위의 방식을 통하여 tensor의 자료형을 변경 및 초기화 할 수 있음

In [85]:
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64


- 서로 다른 자료형에 대한 연산은 더 큰 자료형을 따라감

# f_tensor_operations.py

In [86]:
import torch

In [87]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


- torch.add() : 두 텐서를 합산, + 연산자와 동일

In [88]:
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


- torch.sub() : 두 텐서를 차연산, - 연산자와 동일

In [90]:
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


- torch.mul() : 두 텐서를 곱셈, * 연산자와 동일

In [91]:
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


- torch.div() : 두 텐서를 나누셈, / 연산자와 동일 

# g_tensor_operations_mm.py

In [92]:
import torch

In [93]:
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

tensor(7) torch.Size([])


- torch.dot() : 두 개의 1차원 텐서(벡터) 사이의 내적(dot product)을 계산

In [94]:
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])


- torch.mm() : 두 개의 2차원 텐서(행렬) 사이의 행렬 곱을 계산

In [95]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())

torch.Size([10, 3, 5])


- torch.bmm : 배치(batch) 행렬 간의 곱셈을 계산